CREATE DATABASE IF NOT EXISTS `TESTE_RTE`
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE `TESTE_RTE`;

CREATE TABLE IF NOT EXISTS `TESTE_RTE`.`PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `TESTE_RTE`.`FILHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PESSOA_ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  INDEX `FK_PESSOA_FILHO` (`PESSOA_ID`),
  CONSTRAINT `FK_PESSOA_FILHO` FOREIGN KEY (`PESSOA_ID`) REFERENCES `PESSOA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `TESTE_RTE`.`PESSOA` (`ID`, `NOME`) VALUES
(NULL, 'Pedro'),
(NULL, 'Maria'),
(NULL, 'Marcos'),
(NULL, 'Felipe');

INSERT INTO `TESTE_RTE`.`FILHO` (`ID`, `PESSOA_ID`, `NOME`) VALUES
(NULL, '1', 'Rogerio'),
(NULL, '1', 'Ricardo'),
(NULL, '2', 'Valério'),
(NULL, '2', 'Marta'),
(NULL, '3', 'Carlos'),
(NULL, '3', 'Lucas'),
(NULL, '4', 'Ana'),
(NULL, '4', 'José');