CREATE DATABASE IF NOT EXISTS `TESTE_RTE`
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE `TESTE_RTE`;

CREATE TABLE IF NOT EXISTS `PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(255) NOT NULL,
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `FILHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PESSOA_ID` INT NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
